### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by dizcza** [nicrie/xmca#1]
I'm posting my feedback on behalf of Alex vM, who asked me to have a look at this package.
The feedback is subjective and you may disagree with some if not all suggestions below.

1. In general, the readme is well written. Clear and concise. I'd add a figure(s) though. For instance, after you call `mca.plot()` in your example.
2. Currently, this package is for *developers* or at least those who have python experience. Well, maybe covariance estimation requires knowledge of python and programming skills, but I recommend making sphinx documentation (and publishing it on readthedocs) to bring *users*. You've already written docs for each if not all functions and classes. The only step left is to wrap it in sphinx with default parameters and paths.
3. To give credits to your package and show that it's well maintained, I recommend adding badges (readthedocs, travis build and test coverage). Use CircleCI. [Here](https://github.com/dizcza/pytorch-mighty/blob/master/.circleci/config.yml) is a config example (you need only `build-pip` job since it's the easiest).
4. `tools` folder must be in the `xmca` folder.
5. setup.py install requires must be read from requirements.txt file ([example](https://github.com/dizcza/pytorch-mighty/blob/master/setup.py#L13)) and not hard-coded.
6. GPL-3 license is too restrictive. Consider BSD-3 or even MIT.
7. Each test that involves randomness must start with a `numpy.random.seed`. Currently, you're setting the seed globally. It's not a good idea because the test results depend on the test *order*, which, of course, should not happen.

Good luck!

Best,
Danylo

**Comment by nicrie** [comment]
@dizcza very much appreciated, that's truly helpful! I already had in mind the sphinx documentation, but wasn't sure if it's really the way to go.
Besides I had no idea about points 2, 3 and 4, so your feedback has quite some added value! let me know if I can be of any help to you at some point.
Cheers,
Niclas
