### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by chjones2** [nicrie/xmca#24]
Hello Niclas,

I installed xmca but when I import the library I get this error:
libmkl_rt.so: cannot open shared object file: No such file or directory

any ideas or suggestions would be greatly appreciated.

Cheers,

Charles.

**Comment by chjones2** [comment]
hi 
I found out the installation conflicted with my python environment, particularly with my versions of numpy and cartopy; it seemed to work but actually corrupted the environment. the error in the previous message was a result of that.

I created another simple conda environment and then:
conda install cartopy
pip install xmca

the installation worked and I tested the example in the tutorial.

congratulations on the nice paper by the way, well done. I might bug you with some questions applied to my research problem.

Cheers,

Charles.

**Comment by nicrie** [comment]
Hi Charles, glad it worked! Let me know if you stumble across other issues - always happy to help out!
